### ISSUE TITLE
Large Screens Bounding Box Queries

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nwis-mapper#18]
On large displays, a user (from a zoom level too large) can create a bounding box that 'breaks' the water services query.

When Water Services rejects the too-large query, show an alert to the user that says:

"Please zoom in or select a smaller area."

**Comment by HansVraga** [comment]
![image](https://cloud.githubusercontent.com/assets/12058013/25100480/44c4a5b2-237e-11e7-9358-c446f1a3e821.png)

**Comment by marsmith** [comment]
Fixed.  pass the warning form the services to alert box

![image](https://user-images.githubusercontent.com/6529123/28028301-157df35c-656a-11e7-823c-14c3c31ad5c1.png)
