### ISSUE TITLE
"Active/Inactive" designations for sites

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nwis-mapper#19]
The Active/Inactive designated for Water Data information is unreliable. For users that view the NWIS mapper by viewing the results of a search, create an alert that says:

"Search results in NWIS mapper are using a deprecated active/inactive designation method. To view this area with the current active/inactive information click here."

Show this alert upon initial load of the interface from a search.
"click here" will open the NWIS mapper in a new tab with the extent matching the one they are navigating from. If possible, pass the applicable layers as well so it's immediately clear which sites are active/inactive.

**Comment by marsmith** [comment]
I believe this was being addressed on the services side after discussion with Joe K
