### ISSUE TITLE
Old bookmarked “show sites on map” URLs broke with HTTPS switch

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nwis-mapper#21]
- Mapper reports “there was a problem with the request.”

- Example:

 http://maps.waterdata.usgs.gov/mapper/nwisquery.html?URL=http://waterdata.usgs.gov/usa/nwis/measurements?huc2_cd=04&huc2_cd=07&huc2_cd=09&format=sitefile_output&sort_key=site_no&sitefile_output_format=xml&column_name=agency_cd&column_name=site_no&column_name=station_nm&begin_date=2017-03-23&end_date=2017-04-06&set_logscale_y=1&channel_html_info=0&date_format=YYYY-MM-DD&channel_rdb_info=0&rdb_compression=file&list_of_search_criteria=huc2_cd&column_name=site_tp_cd&column_name=dec_lat_va&column_name=dec_long_va&column_name=agency_use_cd

- Changing the embedded UTL=http to URL=https makes this work just fine.

**Comment by HansVraga** [comment]
@marsmith  Is a redirect to https:// of the Sub-URL at fault possible?

**Comment by HansVraga** [comment]
(as you might expect):
![image](https://cloud.githubusercontent.com/assets/12058013/25101242/77e4053e-2381-11e7-8fa0-d81a8aa044df.png)

**Comment by marsmith** [comment]
This example URL is an old one, this seems to be fixed, closing
