### ISSUE TITLE
WMA Analytics adjustments

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nwis-mapper#43]
- [x] Update client code for both clients
- [x] Ensure vizlab has read access
- [x] submit pull request with updates

WMA suggests combining the Analytics IDs for NWIS Mapper and NWIS Mapper-Water Alert. Details below:

>if there are multiple pieces to a project, they could all be under a single ID (UA-XXXXX), but then filtered views could be created for each piece based on the URLs, in addition to the default view that includes everything.  That way they can easily be looked at together or separately.  Views are what the analytics dashboard keys on.  

>You can just make a pull request with changes to this yaml file: https://github.com/USGS-VIZLAB/internal-analytics/blob/master/data/gaTable.yaml#L779 with whatever new IDs and views the dashboard should use for those applications.  Also, make sure our service account (all-wma-ga@vizlab-142713.iam.gserviceaccount.com) has read access to the new views.

**Comment by HansVraga** [comment]
the vizlab account has read permissions for all WIM GA properties. Checked off that box.

**Comment by marsmith** [comment]
Hans is it your understanding they want us to merge the two seperate entries in the YAML (nwis mapper and wateralert) into one entry? OR just change the analytics ID on wateralert

**Comment by HansVraga** [comment]
Merge 2 into 1.

**Comment by marsmith** [comment]
![image](https://user-images.githubusercontent.com/6529123/61973517-31706600-afb2-11e9-9370-bf436f50c2cd.png)

good enough?

**Comment by HansVraga** [comment]
Yes. If we're ever curious about the breakdown we can look at analytics specifically, but for the water dashboard let's have one entry (Edit: that covers both in the description- like you've already done).

**Comment by marsmith** [comment]
pull request submitted, closing
